/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/001': RouteRecordInfo<'/001', '/001', Record<never, never>, Record<never, never>>,
    '/002': RouteRecordInfo<'/002', '/002', Record<never, never>, Record<never, never>>,
    '/003': RouteRecordInfo<'/003', '/003', Record<never, never>, Record<never, never>>,
    '/004': RouteRecordInfo<'/004', '/004', Record<never, never>, Record<never, never>>,
    '/005': RouteRecordInfo<'/005', '/005', Record<never, never>, Record<never, never>>,
    '/006': RouteRecordInfo<'/006', '/006', Record<never, never>, Record<never, never>>,
    '/007': RouteRecordInfo<'/007', '/007', Record<never, never>, Record<never, never>>,
    '/008': RouteRecordInfo<'/008', '/008', Record<never, never>, Record<never, never>>,
    '/009': RouteRecordInfo<'/009', '/009', Record<never, never>, Record<never, never>>,
    '/010': RouteRecordInfo<'/010', '/010', Record<never, never>, Record<never, never>>,
    '/011': RouteRecordInfo<'/011', '/011', Record<never, never>, Record<never, never>>,
    '/012': RouteRecordInfo<'/012', '/012', Record<never, never>, Record<never, never>>,
    '/013': RouteRecordInfo<'/013', '/013', Record<never, never>, Record<never, never>>,
    '/014': RouteRecordInfo<'/014', '/014', Record<never, never>, Record<never, never>>,
    '/015': RouteRecordInfo<'/015', '/015', Record<never, never>, Record<never, never>>,
    '/016': RouteRecordInfo<'/016', '/016', Record<never, never>, Record<never, never>>,
    '/017': RouteRecordInfo<'/017', '/017', Record<never, never>, Record<never, never>>,
    '/018': RouteRecordInfo<'/018', '/018', Record<never, never>, Record<never, never>>,
    '/019': RouteRecordInfo<'/019', '/019', Record<never, never>, Record<never, never>>,
    '/020': RouteRecordInfo<'/020', '/020', Record<never, never>, Record<never, never>>,
    '/021': RouteRecordInfo<'/021', '/021', Record<never, never>, Record<never, never>>,
  }
}
